### ISSUE TITLE
Flow of control statement executed from the command line

### ISSUE THREAD

**Issue by themagiulio** [bexer/pyeviews#4]
Hi,
I have a problem with the for commands. I know that the for commands should be ran from the .prg file and not from the EViews console.
So, I was wondering if there's a method to use for with pyeviews.
If I try to run:
```
for %j f f_se
series {%j} = @recode({%j} = NA, 0, {%j})
next
```
with pyeviews, it gives me the following error: "Flow of control statement executed from the command line".
 I guess that this happened because pyeviews force EViews to run
`for %j f f_se series {%j} = @recode({%j} = NA, 0, {%j}) next` which isn't runnable from the console...

If there's a way to run for through pyeviews can you please explain me how to do it?

**Comment by bexer** [comment]
You'll have to save it in a program and run that with pyeviews, e.g., `evp.Run("run test.prg", app=...)`.

**Comment by themagiulio** [comment]
Thank you very much
