### ISSUE TITLE
AttributeError: module 'comtypes.gen.EViews' has no attribute 'IManager'

### ISSUE THREAD

**Issue by freddym56** [bexer/pyeviews#5]
I can't seem to start a new eviews app. See my traceback below. Any ideas?
PYEVIEWS V1.0.2, COMTYPES V1.1.9

eviewsapp = pyeviews.GetEViewsApp(instance='new', showwindow=True)
Traceback (most recent call last):

  File "<ipython-input-10-5cc932ed7624>", line 1, in <module>
    eviewsapp = pyeviews.GetEViewsApp(instance='new', showwindow=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyeviews\__init__.py", line 361, in GetEViewsApp
    mgr = CreateObject(version)

  File "C:\ProgramData\Anaconda3\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)

  File "C:\ProgramData\Anaconda3\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)

  File "C:\ProgramData\Anaconda3\lib\site-packages\comtypes\client\__init__.py", line 112, in GetBestInterface
    interface = getattr(mod, itf_name)

AttributeError: module 'comtypes.gen.EViews' has no attribute 'IManager'

**Comment by bexer** [comment]
I don't have a problem when I use the same versions. Can you give more information? More of your program, EViews version, etc?

**Comment by freddym56** [comment]
I'm running Eviews 11 Mar 2 2021 build. This is on a windows 10 machine and running Python version 3.6.5. My script is very simple see below.
```
import pyeviews
eviewsapp = pyeviews.GetEViewsApp(instance='new', showwindow=True)
```

**Comment by bexer** [comment]
I still don't see it. Have you tried updating your Python?

**Comment by bexer** [comment]
Closing this out.

**Comment by freddym56** [comment]
I know you've already closed this but I figured out that this a comtypes issue. To fix we can use the clear_comtypes_cache script.
Open a command prompt window with administrator privilege and run the command below. Note that you must change the clear_comtypes_cache.py directory based on your Python installation.
python "C:\ProgramData\Anaconda3\Scripts\clear_comtypes_cache.py" -y

**Comment by bexer** [comment]
Glad you figured it out.
