### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by qdvictor** [bexer/pyeviews#6]
I just installed pyeviews in my PC. And I am using eviews 10.
I tested the trial codes listed in readme.rst.
But I got the error after run "benchmarked = evp.GetWFAsPython(app=eviewsapp, pagename= 'quarterly', namefilter= 'benchmarked')"
Please check the issue.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-28354c37c46c> in <module>
----> 1 benchmarked = evp.GetWFAsPython(app=eviewsapp, pagename= 'quarterly', namefilter= 'benchmarked')

c:\python38\lib\site-packages\pyeviews\__init__.py in GetWFAsPython(app, wfname, pagename, namefilter)
    295         #get index series
    296         dates = app.GetSeries("@date")
--> 297         idx = pa.DatetimeIndex(dates, freq=spacing + dt_map[freq_str])
    298     elif freq_str == 'W': # might be improved w/ w(*) parsing, ok for now
    299         #get index series

c:\python38\lib\site-packages\pandas\core\indexes\datetimes.py in __new__(cls, data, freq, tz, normalize, closed, ambiguous, dayfirst, yearfirst, dtype, copy, name)
    330         name = maybe_extract_name(name, data, cls)
    331 
--> 332         dtarr = DatetimeArray._from_sequence_not_strict(
    333             data,
    334             dtype=dtype,

c:\python38\lib\site-packages\pandas\core\arrays\datetimes.py in _from_sequence_not_strict(cls, data, dtype, copy, tz, freq, dayfirst, yearfirst, ambiguous)
    372         if inferred_freq is None and freq is not None:
    373             # this condition precludes `freq_infer`
--> 374             cls._validate_frequency(result, freq, ambiguous=ambiguous)
    375 
    376         elif freq_infer:

c:\python38\lib\site-packages\pandas\core\arrays\datetimelike.py in _validate_frequency(cls, index, freq, **kwargs)
    951         """
    952         # TODO: this is not applicable to PeriodArray, move to correct Mixin
--> 953         inferred = index.inferred_freq
    954         if index.size == 0 or inferred == freq.freqstr:
    955             return None

c:\python38\lib\site-packages\pandas\core\arrays\datetimelike.py in inferred_freq(self)
    915             return None
    916         try:
--> 917             return frequencies.infer_freq(self)
    918         except ValueError:
    919             return None

c:\python38\lib\site-packages\pandas\tseries\frequencies.py in infer_freq(index, warn)
    193         index = pd.DatetimeIndex(index)
    194 
--> 195     inferer = _FrequencyInferer(index, warn=warn)
    196     return inferer.get_freq()
    197 

c:\python38\lib\site-packages\pandas\tseries\frequencies.py in __init__(self, index, warn)
    210         if hasattr(index, "tz"):
    211             if index.tz is not None:
--> 212                 self.i8values = tzconversion.tz_convert_from_utc(
    213                     self.i8values, index.tz
    214                 )

c:\python38\lib\site-packages\pandas\_libs\tslibs\tzconversion.pyx in pandas._libs.tslibs.tzconversion.tz_convert_from_utc()

c:\python38\lib\site-packages\pandas\_libs\tslibs\tzconversion.pyx in pandas._libs.tslibs.tzconversion._tz_convert_from_utc()

c:\python38\lib\site-packages\pandas\_libs\tslibs\timezones.pyx in pandas._libs.tslibs.timezones.get_dst_info()

AttributeError: 'NoneType' object has no attribute 'total_seconds'

**Comment by bexer** [comment]
This is related to the pywin32 library used in this version of pyeviews. I'm currently working on a fix.

**Comment by bexer** [comment]
This has been fixed in the latest version, pyeviews 1.0.4.
