### ISSUE TITLE
AttributeError: module 'pandas.core' has no attribute 'panel'

### ISSUE THREAD

**Issue by azacha** [bexer/pyeviews#7]
If you try to use a numpy array, list, dict as data in` PutPythonAsWF(data, app=eviewsapp, newwf=False)`, we get an error in this elif statement:
` elif isinstance(obj, pa.core.panel.Panel):`
 
 Remove line 211 to 224 in __init__.py fixes those error and allows you to load an numpy array into eviews.

**Comment by bexer** [comment]
This has been fixed in the latest version, pyeviews 1.0.4.
