### ISSUE TITLE
Flow of control statement executed from the command line

### ISSUE THREAD

**Issue by Berenge** [bexer/pyeviews#8]
Hi,
I have a problem with the for commands. I want to add a .prg file to my workfile after filling it with serie using PutPythonAsWF now I want to include the file to call subroutines. Is this possible on pyeviews?
Actually i have issue "Flow of control statement executed from the command line"

**Comment by bexer** [comment]
You can call the subroutine in an EViews program, and then call that program with Run in pyeviews.

**Comment by Berenge** [comment]
I did it by doing a run <path to .prg file> I see the subroutine but when I do a call on the next line I get the same error as above but on the Call statement

**Comment by bexer** [comment]
Can you give an example of the code you're trying to run?

**Comment by Berenge** [comment]
Yes, for example :

import numpy as np
import pandas as pa
import pyeviews as evp

eviewsapp = evp.GetEViewsApp(instance='new',showwindow=True)
dtsa = pa.date_range('1998', periods = 3, freq = 'A')
benchmark = pa.Series([4000.,4161.4,np.nan], index=dtsa, name = 'benchmark')
dtsq = pa.date_range('1998q1', periods = 12, freq = 'Q')
indicator = pa.Series([98.2, 100.8, 102.2, 100.8, 99., 101.6, 102.7, 101.5, 100.5, 103., 103.5, 101.5], index = dtsq, name = 'indicator')
evp.PutPythonAsWF(benchmark, app=eviewsapp)
evp.PutPythonAsWF(indicator,app=eviewsapp,newwf=False)

evp.Run('pageselect Untitled', app=eviewsapp)
evp.Run('pagerename Untitled annual', app=eviewsapp)
evp.Run('pageselect Untitled1', app=eviewsapp)
evp.Run('pagerename Untitled1 quarterly',app=eviewsapp)

evp.Run('copy(rho=.7, c=chowlins, overwrite) annual\\benchmark quarterly\\benchmarked @indicatorindicator', app=eviewsapp)
evp.Run('copy(rho=.7, c=chowlins, overwrite) annual\\benchmark quarterly\\benchmarked1 @indicatorindicator', app=eviewsapp)
evp.Run('pageselect quarterly', app=eviewsapp)
evp.Run('run <path_file>\\test.prg', app=eviewsapp)
evp.Run('call power(benchmarked1,benchmarked,2)', app=eviewsapp)

And the test.prg content  is :

subroutine power(series v, series y, scalar p)
v = y^p
endsub

**Comment by bexer** [comment]
You need to call the subroutine from within another EViews program.

**Comment by Berenge** [comment]
Yes, it works. Thank you.

**Comment by bexer** [comment]
Glad I could help
